version: 2
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-
          - v1-dependencies-
      - run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
          ls
          TAG=v0.1.$CIRCLE_WORKFLOW_ID
          sed -i -e 's/VERSION/'$TAG'/g' package.json
          cat package.json
          npm install
          sed -i -e 's/VERSION/'$TAG'/g' package.json
          npm publish
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
      - persist_to_workspace:
          root: ~/repo
          paths: .
workflows:
  version: 2
  build_publish:
    jobs:
      - build:
          filters:
            branches:
              only: master
          