version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
    test:
      docker:
        - image: circleci/node:4.8.2-jessie
      working_directory: ~/repo
      steps:
        - checkout
        - run: |
            sed 's,ENV_CHAIN_ID,'$CHAIN_ID',; s,ENV_KEY_PROVIDER,'$KEY_PROVIDER',; s,ENV_HTTP_ENDPOINT,'$HTTP_ENDPOINT',; s,ENV_WALLET_ENDPOINT,'$WALLET_ENDPOINT',;' test/.envtemplate > .env
            cat .env
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
            filters:
              branches:
                only: master