version: 2
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - run: |
          echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - persist_to_workspace:
          root: ~/repo
          paths: .

  build:
    <<: *defaults 
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-
          - v1-dependencies-
      - run: |
          npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    <<: *defaults 
    steps:
      - attach_workspace:
          at: ~/repo
      - run: |
            TAG=v0.1.$CIRCLE_WORKFLOW_ID
            npm publish --tag $TAG
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master